### PR TITLE
Change initialization of URL class for browser compatibility

### LINKED ISSUE #105: TypeError: URL is not a constructor :(
After #104, armlet still errors in the browser at the same line as before:

```
module.exports.defaultApiUrl = new URL(defaultApiUrl)
```

This time the error is:

```
Uncaught TypeError: URL is not a constructor
```

Which is surprising because URL is supposed to be a built-in class and I'm convinced I had it working exactly like that. Tested in Safari and Chrome.

### PR DESCRIPTION
**Pull request by muellerberndt**
Fixes #105.

### CODE REVIEW

**Review by birdofpreyru — COMMENTED** [review]
Looks good to me, but somebody should try it in action in both browser and node environments

**Comment by muellerberndt** [comment]
Works I think but I'm not an npm expert, please double-check :)

**Comment by birdofpreyru** [comment]
Well, I actually never really ran Armlet myself, thus not sure how to check it in action. But, as JS expert I believe, it should make the trick, save some unfortunate tiny misprint :)

**Review by nbanmp — APPROVED** [review]
This works with node! As it sounds like it works well on the browser for you, I'll merge it!

**Comment by vdenisov-pro** [comment]
The problem occurs because `url.URL` is `undefined` (read more in this [comment](https://github.com/ConsenSys/armlet/issues/105#issuecomment-673060135)).

**Pull request merged**
