### PR TITLE
Add human readable error message on status 401

### PR DESCRIPTION
**Pull request by daniyarchambylov**

### CODE REVIEW

**Review by rocky — DISMISSED** [review]
LGTM - thanks

**Review by fgimenez — DISMISSED** [review]
:+1:

**Review by rocky — COMMENTED** [review]
One thing that has come up that I forgot. Does this show a traceback in the result? 
If so that's not what I think we want. There is no value in showing a traceback when MythX credentals are wrong. 

On the other hand, there will be  times when we do have unexpected or unexplainable situations where a traceback _would_ be helpful.

**Review by rocky — APPROVED** [review]
Although this is possibly not the most stylish way to removec the traceback it works. 

Since time for release is pressing let's revisit after the next armlet release.

**Pull request merged**
